<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
	  <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
	  <OptionExplicit>On</OptionExplicit>
	  <OptionCompare>Binary</OptionCompare>
	  <OptionStrict>Off</OptionStrict>
	  <OptionInfer>On</OptionInfer>
  </PropertyGroup>
  <ItemGroup>
    <Import Include="Microsoft.VisualBasic" />
    <Import Include="System.Collections.Generic" />
    <Import Include="System.Collections" />
    <Import Include="System.Diagnostics" />
    <Import Include="System" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="My Project\licenses.licx" />
    <None Update="PivotTableTemplate.xlsx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
	  <PackageReference Include="DevExpress.Document.Processor" Version="24.2.5" />
	  <PackageReference Include="DevExpress.Drawing.Skia" Version="24.2.5" />
	  <PackageReference Include="DevExpress.Win" Version="24.2.5" />
  </ItemGroup>
</Project>